### ISSUE TITLE
Auras Buffs [Show only dispellable] don't work. 

### ISSUE THREAD

**Issue by pmbednarczyk** [vendethiel/GladiusEx#64] opened 2023-01-16 20:09 UTC
I have found bug which I think is quite important (at least for me ;)).

GladiusEx Menu -> Arenas -> Auras -> Buffs

When 'Show only dispellable' is checked, then buffs don't show at all then.
Is there a chance to fix it? <3 Love GladiusEx.

**Comment by vendethiel** [comment] 2023-01-16 20:36
Duplicate of #62. Need to find some time to look into it, I think LibCanDispel might be broken.

**Comment by vendethiel** [comment] 2023-01-16 20:39
I'll keep the other issue.

**Closed by vendethiel** 2023-01-16 20:39 UTC
